apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-lab-deployment
  namespace: web  # Specify the namespace here
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-lab
  template:
    metadata:
      labels:
        app: argocd-lab
    spec:
      containers:
      - name: argocd-lab
        image: jmuachifi/argocd-lab:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-lab-service
  namespace: web  # Specify the namespace here
spec:
  type: NodePort
  selector:
    app: argocd-lab
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
